fixes after code review
YellowPipe/tic-tac-toe pull request #2
Opened 2019-02-22 15:04 UTC by YellowPipe

2019-03-11 21:53 UTC, heyapricot requested changes
# Let's polish this gem

Hello! 👋🏼 Tic tac toe looks nice. I liked the menu you built. That said, I found some areas where we could improve performance and scalability. Your tic-tac-toe could end up being used by millions of users. Who knows? 

So, please address the comments I've left and after that send a new code review request. As always, feel free to reach over crisp for further discussion. Thank you!

2019-03-11 21:53 UTC, heyapricot commented on lib/game.rb
> -	end
I like the idea of this. Just be careful with recursion (What happens when somebody enters the wrong symbol A LOT of times. You could fill the stack and program crashes ☠️)

2019-03-11 21:53 UTC, heyapricot commented on lib/game.rb
> +			return player_symbol
You can omit the final else and just have the method return the player_symbol.
Also, ruby methods return the last called variable so you can omit the return statement and just type the variable name

2019-03-11 21:53 UTC, heyapricot commented on lib/game.rb
> +			add_players if @player1 == nil && @player2 == nil
Is the conditional right? Do you want to add players only of BOTH players are missing? One player missing is enough reason to add the players again don't you think?

2019-03-11 21:53 UTC, heyapricot commented on lib/game.rb
> +			add_board if @board == nil
Favor the use of `.nil?`

2019-03-11 21:53 UTC, heyapricot commented on lib/game.rb
> +	end
This method does two things, validates input and then writes to the board.
The validation part is a bit messy, it relies on the board_valid input method but also on some conditionals and string substitution with a regular expression. It does all these alternating with writing a move to the board. 

Wouldn't it be better to have a single method that deals with the validation for `move` and once we are sure the move input is valid we pass it to the `move` method?

2019-03-11 21:53 UTC, heyapricot commented on lib/game.rb
> +		until @board.player_won?(@player1.symbol) || @board.player_won?(@player2.symbol) || @board.full? || @wanna_quit
Do we need to check against a specific player? For the game to end we just need to check if there is a sequence of symbols in a row, a column or a diagonal. Once we know there is a sequence we can determine the winner based on the symbol or the current turn. 

Checking for a specific player symbol twice is not optimal

2019-03-11 21:53 UTC, heyapricot commented on lib/board.rb
> +    end
In general, avoid naming variables with only one character. Find the balance between being brief and explaining what a variable does/stores

2019-03-11 21:53 UTC, heyapricot commented on lib/board.rb
> +	end
You never use this method inside the `board` object. You could validate every move before it is written or you could put the validator outside and assume you are getting a valid input. Either way is fine. Just pick one strategy, not half validation in one object and the other half on another. (If you assume you are getting a valid input that doesn't mean you shouldn't protect against possible errors like index out of reach).

2019-03-11 21:53 UTC, heyapricot commented on lib/board.rb
> +	end
Exactly what I meant with 'half validation'. 
Choose one strategy:
- Validate the input on `Game` (outside the `board` object) and then pass the input to the board
- Validate input on `board` (Different methods for validation maybe?) and run the validators before a move is made. Then `Game` just has to call board.make_move (or similar). [I prefer this strategy but is up to you]

2019-03-11 21:53 UTC, heyapricot commented on lib/board.rb
> +		@matrix = Array.new(dim**2)
You forgot the `@` before `dim`. Also, do you really need to call `Array.new(number)`? I mean, is it necessary that you have an array full of `nil` values?

2019-03-20 10:59 UTC, merged

2019-03-20 11:14 UTC, YellowPipe commented on lib/game.rb
> +			add_players if @player1 == nil && @player2 == nil
Well, the method adds 2 players so it doesn't really matter

2019-03-20 11:15 UTC, YellowPipe commented on lib/game.rb
> +			add_players if @player1 == nil && @player2 == nil
Changed it to OR statement though