changes after CR3
YellowPipe/tic-tac-toe pull request #3
Opened 2019-03-20 13:26 UTC by YellowPipe

2019-03-21 21:16 UTC, heyapricot requested changes
# Almost there, let's delegate the right responsibilities to each object

👋🏼 Hello! I have some suggestions about the way the moves are written to the board. Please address my annotations and after that submit a new code review request. Thanks!

2019-03-21 21:16 UTC, heyapricot commented on lib/board.rb
> +        arr  += Array.new(1) { |element1| Array.new(dim){|element2|  element2*(dim-1) + (dim-1)}}
If you want to make it easier to understand, [Range and step could help with that](https://ruby-doc.org/core-2.6.2/Range.html#method-i-step)

2019-03-21 21:16 UTC, heyapricot commented on lib/game.rb
>  			system "clear"
This line could be added to the top of `board.print_board`

2019-03-21 21:16 UTC, heyapricot commented on lib/board.rb
>  	end
What's the use of `print " "` If you want a line break you can use puts directly. Also, there is string interpolation

2019-03-21 21:16 UTC, heyapricot commented on lib/board.rb
>  	end
[Also, take a look at this stack overflow article about using each_slice .with_index.](https://stackoverflow.com/questions/5983977/ruby-array-each-slice-with-index) Could help removing the `counter`

2019-03-21 21:16 UTC, heyapricot commented on lib/game.rb
>  		else
I don't think it is the responsibility of the `board` object to validate the input. 
Can we split this method? The actions that happen here are:
1. You get input from the user through the console
2. You validate the input
3. If the input is valid you send it to the board, else you request it again
4. You 'write' to the board

2019-03-22 09:20 UTC, YellowPipe commented on lib/game.rb
>  			system "clear"
Which line?

2019-03-22 09:27 UTC, YellowPipe commented on lib/board.rb
>  	end
" " adds a space before alphabet on the top of the board so it matches the actual positions

2019-03-22 09:45 UTC, merged